### ISSUE TITLE
 [BUG] Angular language service hangs when using Taiga

### ISSUE THREAD

**Issue by sdurnov** [taiga-family/taiga-ui#238]
# 🐞 Bug report

### Description

When opening a project which uses Taiga, the ALS extension gives multiple error messages.
![изображение](https://user-images.githubusercontent.com/32732457/109005632-37ad5380-76bb-11eb-84dd-4f0e1c1a3d25.png)

### Reproduction

Using the most recent ALS plugin for VSCode, open a project with Taiga in Code.

### Expected behavior

ALS should work

### Versions

-   OS: Windows 10 x64
-   Angular 11
-   All Taiga packages listed in get started guide

### Additional context

Here is an ALS log from VSCode
```

[Info  - 16:10:23] Angular language server process ID: 9816
[Info  - 16:10:23] Using typescript/lib/tsserverlibrary v4.1.5 from c:\Users\serge\.vscode\extensions\angular.ng-template-11.2.3\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 16:10:23] Using @angular/language-service/bundles/ivy v11.2.2 from c:\Users\serge\.vscode\extensions\angular.ng-template-11.2.3\node_modules\@angular\language-service\bundles\ivy.js
[Info  - 16:10:23] Log file: c:\Users\serge\AppData\Roaming\Code\logs\20210224T161012\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 16:10:24] Disabling language service for c:/Projects/website/libs/ui/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
[Info  - 16:10:38] Disabling language service for c:/Projects/website/libs/ui/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
[Error - 16:10:41] No config file for c:/Projects/website/libs/ui/src/lib/nav/nav.component.html
[Error - 16:10:48] Failed to run ngcc for c:/Projects/website/libs/ui/tsconfig.lib.json:
    ngcc for c:/Projects/website/libs/ui/tsconfig.lib.json returned exit code 1, stderr: [33mWarning:[0m Entry point 'angular2-text-mask' contains deep imports into 'C:/Projects/website/node_modules/text-mask-core/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[31mError:[0m Failed to compile entry-point @taiga-ui/addon-mobile/components/mobile-calendar-dialog (fesm2015 as esm2015) due to compilation errors:
[96mnode_modules/@taiga-ui/addon-mobile/components/mobile-calendar/mobile-calendar.module.d.ts[0m:[93m1[0m:[93m22[0m - [91merror[0m[90m NG6002: [0mAppears in the NgModule.imports of TuiMobileCalendarDialogModule, but could not be resolved to an NgModule class.

This likely means that the library (@taiga-ui/addon-mobile/components/mobile-calendar) which declares TuiMobileCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

[7m1[0m export declare class TuiMobileCalendarModule {
[7m [0m [91m                     ~~~~~~~~~~~~~~~~~~~~~~~[0m

[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
Error: There are still unprocessed tasks in the queue and no tasks are currently in progress, yet the queue did not return any available tasks: ParallelTaskQueue
  All tasks completed: true
  Unprocessed tasks (0): 
  In-progress tasks (0): 
  Blocked tasks (0): 
    at ClusterMaster.maybeDistributeWork (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:134:27)
    at ClusterMaster.onWorkerTaskCompleted (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:228:18)
    at ClusterMaster.onWorkerMessage (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:197:33)
    at c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (c:\Projects\website\node_modules\tslib\tslib.js:143:27)
    at Object.next (c:\Projects\website\node_modules\tslib\tslib.js:124:57)
    at c:\Projects\website\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (c:\Projects\website\node_modules\tslib\tslib.js:113:16)
    Language service will remain disabled.
[Info  - 16:10:48] Enabling Ivy language service for c:/Projects/website/libs/ui/tsconfig.lib.json.
[Error - 16:10:53] Failed to run ngcc for c:/Projects/website/libs/ui/tsconfig.spec.json:
    ngcc for c:/Projects/website/libs/ui/tsconfig.spec.json returned exit code 1, stderr: [33mWarning:[0m Entry point 'angular2-text-mask' contains deep imports into 'C:/Projects/website/node_modules/text-mask-core/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[31mError:[0m Failed to compile entry-point @taiga-ui/addon-mobile/components/mobile-calendar-dialog (fesm2015 as esm2015) due to compilation errors:
[96mnode_modules/@taiga-ui/addon-mobile/components/mobile-calendar/mobile-calendar.module.d.ts[0m:[93m1[0m:[93m22[0m - [91merror[0m[90m NG6002: [0mAppears in the NgModule.imports of TuiMobileCalendarDialogModule, but could not be resolved to an NgModule class.

This likely means that the library (@taiga-ui/addon-mobile/components/mobile-calendar) which declares TuiMobileCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

[7m1[0m export declare class TuiMobileCalendarModule {
[7m [0m [91m                     ~~~~~~~~~~~~~~~~~~~~~~~[0m

[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
Error: There are still unprocessed tasks in the queue and no tasks are currently in progress, yet the queue did not return any available tasks: ParallelTaskQueue
  All tasks completed: true
  Unprocessed tasks (0): 
  In-progress tasks (0): 
  Blocked tasks (0): 
    at ClusterMaster.maybeDistributeWork (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:134:27)
    at ClusterMaster.onWorkerTaskCompleted (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:228:18)
    at ClusterMaster.onWorkerMessage (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:197:33)
    at c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (c:\Projects\website\node_modules\tslib\tslib.js:143:27)
    at Object.next (c:\Projects\website\node_modules\tslib\tslib.js:124:57)
    at c:\Projects\website\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (c:\Projects\website\node_modules\tslib\tslib.js:113:16)
    Language service will remain disabled.
[Info  - 16:10:53] Enabling Ivy language service for c:/Projects/website/libs/ui/tsconfig.spec.json.
[Error - 16:10:58] Failed to run ngcc for c:/Projects/website/libs/ui/tsconfig.lib.json:
    ngcc for c:/Projects/website/libs/ui/tsconfig.lib.json returned exit code 1, stderr: [33mWarning:[0m Entry point 'angular2-text-mask' contains deep imports into 'C:/Projects/website/node_modules/text-mask-core/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[31mError:[0m Failed to compile entry-point @taiga-ui/addon-mobile/components/mobile-calendar-dialog (fesm2015 as esm2015) due to compilation errors:
[96mnode_modules/@taiga-ui/addon-mobile/components/mobile-calendar/mobile-calendar.module.d.ts[0m:[93m1[0m:[93m22[0m - [91merror[0m[90m NG6002: [0mAppears in the NgModule.imports of TuiMobileCalendarDialogModule, but could not be resolved to an NgModule class.

This likely means that the library (@taiga-ui/addon-mobile/components/mobile-calendar) which declares TuiMobileCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

[7m1[0m export declare class TuiMobileCalendarModule {
[7m [0m [91m                     ~~~~~~~~~~~~~~~~~~~~~~~[0m

[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
Error: There are still unprocessed tasks in the queue and no tasks are currently in progress, yet the queue did not return any available tasks: ParallelTaskQueue
  All tasks completed: true
  Unprocessed tasks (0): 
  In-progress tasks (0): 
  Blocked tasks (0): 
    at ClusterMaster.maybeDistributeWork (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:134:27)
    at ClusterMaster.onWorkerTaskCompleted (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:228:18)
    at ClusterMaster.onWorkerMessage (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:197:33)
    at c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (c:\Projects\website\node_modules\tslib\tslib.js:143:27)
    at Object.next (c:\Projects\website\node_modules\tslib\tslib.js:124:57)
    at c:\Projects\website\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (c:\Projects\website\node_modules\tslib\tslib.js:113:16)
    Language service will remain disabled.
[Info  - 16:10:58] Enabling Ivy language service for c:/Projects/website/libs/ui/tsconfig.lib.json.
[Error - 16:11:03] Failed to run ngcc for c:/Projects/website/libs/ui/tsconfig.spec.json:
    ngcc for c:/Projects/website/libs/ui/tsconfig.spec.json returned exit code 1, stderr: [33mWarning:[0m Entry point 'angular2-text-mask' contains deep imports into 'C:/Projects/website/node_modules/text-mask-core/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[31mError:[0m Failed to compile entry-point @taiga-ui/addon-mobile/components/mobile-calendar-dialog (fesm2015 as esm2015) due to compilation errors:
[96mnode_modules/@taiga-ui/addon-mobile/components/mobile-calendar/mobile-calendar.module.d.ts[0m:[93m1[0m:[93m22[0m - [91merror[0m[90m NG6002: [0mAppears in the NgModule.imports of TuiMobileCalendarDialogModule, but could not be resolved to an NgModule class.

This likely means that the library (@taiga-ui/addon-mobile/components/mobile-calendar) which declares TuiMobileCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

[7m1[0m export declare class TuiMobileCalendarModule {
[7m [0m [91m                     ~~~~~~~~~~~~~~~~~~~~~~~[0m

[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
[33mWarning:[0m Skipping processing of @taiga-ui/addon-mobile/components/mobile-calendar-dialog because its dependency @taiga-ui/addon-mobile/components/mobile-calendar-dialog failed to compile.
Error: There are still unprocessed tasks in the queue and no tasks are currently in progress, yet the queue did not return any available tasks: ParallelTaskQueue
  All tasks completed: true
  Unprocessed tasks (0): 
  In-progress tasks (0): 
  Blocked tasks (0): 
    at ClusterMaster.maybeDistributeWork (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:134:27)
    at ClusterMaster.onWorkerTaskCompleted (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:228:18)
    at ClusterMaster.onWorkerMessage (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:197:33)
    at c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (c:\Projects\website\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (c:\Projects\website\node_modules\tslib\tslib.js:143:27)
    at Object.next (c:\Projects\website\node_modules\tslib\tslib.js:124:57)
    at c:\Projects\website\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (c:\Projects\website\node_modules\tslib\tslib.js:113:16)
    Language service will remain disabled.
[Info  - 16:11:03] Enabling Ivy language service for c:/Projects/website/libs/ui/tsconfig.spec.json.
```

**Comment by waterplea** [comment]
Is it still relevant? I know @MarsiBarsi is using VSCode to work with Taiga and with projects that use Taiga. Not sure if he's using ALS. I saw issues with ngcc in live IDE — we had to disable Ivy on StackBlitz to get it working. But I never faced such issues with WebStorm. @MarsiBarsi can you check this on your machine?

**Comment by MarsiBarsi** [comment]
Seems to be working on my ALS 12.0.2 in VS Code (1.56.2) on Mac OS

**Comment by waterplea** [comment]
@sdurnov can you bump versions and check again?

**Comment by waterplea** [comment]
There's no response and we were not able to reproduce, so I'm closing this. Feel free to reopen if you face with it again.
