### ISSUE TITLE
🐞 - `Svg` throws SSR error `ReferenceError: DOMParser is not defined`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#5316]
### Playground Link

https://github.com/taiga-family/maskito/actions/runs/6109538179/job/16581202078?pr=484

### Description

```
ReferenceError: DOMParser is not defined
    at setFallbackForGradientFill (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:1552647)
    at Object.tuiSvgLinearGradientProcessor [as contentProcessor] (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:1551676)
    at TuiSvgComponent.sanitize (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:1740212)
    at MapSubscriber.project (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:1740769)
    at MapSubscriber._next (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:3437543)
    at MapSubscriber.next (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:3397377)
    at CatchSubscriber.notifyNext (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:34064[22](https://github.com/taiga-family/maskito/actions/runs/6109538179/job/16581202078?pr=484#step:5:23))
    at SimpleInnerSubscriber2._next (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:3405718)
    at SimpleInnerSubscriber2.next (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:3397377)
    at Observable._subscribe (/home/runner/work/maskito/maskito/dist/demo/server/main.js:1:3477744)
```

Probably relates to:
* https://github.com/taiga-family/taiga-ui/pull/5227

### Angular version

12

### Taiga UI version

3.43.0

**Comment by nsbarsukov** [comment]
The issue has high priority because it blocks Maskito repo from any further Taiga UI updates.
