### ISSUE TITLE
🐞 - TypeError: requestAnimationFrame is not a function

### ISSUE THREAD

**Issue by grizlizli** [taiga-family/taiga-ui#6545]
### Description

Hi!

I have started a new project with Angular 17.1.1.

I have added Taiga UI but when I run the application in local with ng serve, I get the error (in terminal, not in browser):

```
Application bundle generation complete. [1.178 seconds]
Page reload sent to client(s).
ERROR TypeError: requestAnimationFrame is not a function
    at _Observable.eval (c:/Users/mrkrs/Workspace/akvaterm/node_modules/@ng-web-apis/common/fesm2015/ng-web-apis-common.js:25:18)
    at _Observable._trySubscribe (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/Observable.js:37:25)
    at eval (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/Observable.js:31:30)
    at errorContext (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/util/errorContext.js:19:9)
    at _Observable.subscribe (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/Observable.js:22:9)
    at eval (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/operators/share.js:58:35)
    at OperatorSubscriber.eval (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/util/lift.js:10:28)
    at eval (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/Observable.js:26:30)
    at errorContext (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/util/errorContext.js:19:9)
    at _Observable.subscribe (c:/Users/mrkrs/Workspace/akvaterm/node_modules/rxjs/dist/esm/internal/Observable.js:22:9)
```

As I understand, I should install @ng-web-apis/common dependency and I did but I am not sure what to do next :)

Kindest regards

### Angular version

17.1.1

### Taiga UI version

3.63.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by mouadennaciri** [comment]
It's because you're using SSR. You need to install the `@ng-web-apis/universal` dependency and add `UNIVERSAL_PROVIDERS` to the providers array in the `app.config.ts` file.
[`@ng-web-apis/universal` README](https://github.com/taiga-family/ng-web-apis/tree/main/libs/universal)

**Comment by grizlizli** [comment]
Thanks for the support. Managed to solve the issue.

Keep up the amazing work!
